INSERT INTO users (username, first_name, last_name, email, age, password) VALUES ('даниил.субботин', 'Зинаида', 'Юдина', 'валерия.прохоров@gmail.com', 45, '$2a$10$RqL/u1WkfS0lIFPwAzm6D.t/KRLWWiq8ui6BUnLWjW4zQibmQy4lq');
INSERT INTO user_roles (user_id, role_id) VALUES (1, 1);
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (1, 'Налог на имущество', 3668.42, '2024-12-20', 'PAID');
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (1, 'Налог на доход', 5039.42, '2025-02-03', 'PENDING');
INSERT INTO properties (user_id, type, description, value) VALUES (1, 'Автомобиль', 'Earth Wind and Fire', 777881.13);
INSERT INTO users (username, first_name, last_name, email, age, password) VALUES ('максим.тихонов', 'Георгий', 'Рожкова', 'юрии.селиверстова@mail.ru', 20, '$2a$10$zjapi8XsAQIRmA8I0dX5He8QR2Ry9FZy82B.t1OYLstyMQ/VqNB/u');
INSERT INTO user_roles (user_id, role_id) VALUES (2, 1);
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (2, 'Налог на имущество', 7865.00, '2024-12-31', 'PAID');
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (2, 'Налог на доход', 6335.14, '2025-02-02', 'PENDING');
INSERT INTO properties (user_id, type, description, value) VALUES (2, 'Автомобиль', 'Van Halen', 4535639.52);
INSERT INTO users (username, first_name, last_name, email, age, password) VALUES ('ольга.орлова', 'Роман', 'Красильников', 'андреи.королева@mail.ru', 52, '$2a$10$HYiya2lkexDWMdAxPVLr2e/E9FrrnMpQW/lYWmkhEYwQFReBmPtHe');
INSERT INTO user_roles (user_id, role_id) VALUES (3, 1);
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (3, 'Налог на доход', 8074.57, '2024-12-22', 'PAID');
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (3, 'Налог на имущество', 2168.66, '2025-01-21', 'PENDING');
INSERT INTO properties (user_id, type, description, value) VALUES (3, 'Автомобиль', 'Lynyrd Skynyrd', 4561642.61);
INSERT INTO users (username, first_name, last_name, email, age, password) VALUES ('алла.виноградова', 'София', 'Никонов', 'варвара.королев@ya.ru', 32, '$2a$10$1qIwZDnthmYYWe2q5YmaLunJT33ecyn1wp6MBES9JwGfA70xSTjoa');
INSERT INTO user_roles (user_id, role_id) VALUES (4, 1);
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (4, 'Налог на доход', 2324.62, '2024-12-14', 'PAID');
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (4, 'Налог на имущество', 6496.79, '2025-01-19', 'PENDING');
INSERT INTO properties (user_id, type, description, value) VALUES (4, 'Автомобиль', 'Nirvana', 2675711.52);
INSERT INTO users (username, first_name, last_name, email, age, password) VALUES ('игорь.данилов', 'Денис', 'Суворова', 'любовь.турова@hotmail.com', 55, '$2a$10$1c3J7lr4oCMVPeLFDE5onuq3bk7la2/JzFmz2M0MA28NJMZNKZ7Km');
INSERT INTO user_roles (user_id, role_id) VALUES (5, 1);
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (5, 'Налог на имущество', 7711.59, '2025-01-13', 'PAID');
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (5, 'Налог на доход', 5513.66, '2024-12-28', 'PENDING');
INSERT INTO properties (user_id, type, description, value) VALUES (5, 'Квартира', '###### Россия, Иркутск, пр. Гоголя, 931 кв. 173', 4971692.18);
INSERT INTO users (username, first_name, last_name, email, age, password) VALUES ('людмила.кузьмин', 'Григорий', 'Гаврилова', 'борис.назаров@gmail.com', 19, '$2a$10$.zQEiqxnIGzHuVixQrM4UOFZIcHjO2HwzdpOeCWELWA4aFZLg8ip.');
INSERT INTO user_roles (user_id, role_id) VALUES (6, 1);
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (6, 'Налог на доход', 2944.74, '2025-02-08', 'PAID');
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (6, 'Налог на имущество', 8152.16, '2025-01-25', 'PENDING');
INSERT INTO properties (user_id, type, description, value) VALUES (6, 'Квартира', '###### Россия, Ставрополь, Северная пл., 286 кв. 006', 2072398.79);
INSERT INTO users (username, first_name, last_name, email, age, password) VALUES ('иван.наумова', 'Анжелика', 'Зуев', 'алена.молчанов@mail.ru', 49, '$2a$10$lUifKeIcAowiyN0jveRD1e8hWHV1JfHJq9WVAVI7nIlJZOFvhXGvy');
INSERT INTO user_roles (user_id, role_id) VALUES (7, 1);
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (7, 'Налог на доход', 8484.08, '2025-01-15', 'PAID');
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (7, 'Налог на имущество', 4234.25, '2025-01-09', 'PENDING');
INSERT INTO properties (user_id, type, description, value) VALUES (7, 'Автомобиль', 'Little Feat', 4629866.60);
INSERT INTO users (username, first_name, last_name, email, age, password) VALUES ('арина.орехова', 'Варвара', 'Сысоева', 'алевтина.кулагина@mail.ru', 36, '$2a$10$cKRJy92QQBA1qEthOGhfJezbowzUYnzfIbZqVAJTALWRpUu1joRyy');
INSERT INTO user_roles (user_id, role_id) VALUES (8, 1);
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (8, 'Налог на доход', 1246.16, '2024-12-28', 'PAID');
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (8, 'Налог на имущество', 9139.43, '2024-12-31', 'PENDING');
INSERT INTO properties (user_id, type, description, value) VALUES (8, 'Квартира', '###### Россия, Самара, площадь Строительная, 228', 3476983.88);
INSERT INTO users (username, first_name, last_name, email, age, password) VALUES ('герман.ермакова', 'Оксана', 'Боброва', 'виктор.зыкова@gmail.com', 53, '$2a$10$zkuBs4WvX1RQx8XiQjTXRu8sd4ylxm4QUb1ciM4d5d2nTnATGwPzi');
INSERT INTO user_roles (user_id, role_id) VALUES (9, 1);
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (9, 'Налог на доход', 1677.66, '2025-01-16', 'PAID');
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (9, 'Налог на имущество', 2018.66, '2025-02-01', 'PENDING');
INSERT INTO properties (user_id, type, description, value) VALUES (9, 'Квартира', '###### Россия, Махачкала, Комарова пр., 967 кв. 921', 2634229.01);
INSERT INTO users (username, first_name, last_name, email, age, password) VALUES ('антон.беляков', 'Даниил', 'Вишнякова', 'юрии.виноградова@hotmail.com', 46, '$2a$10$AZNv101.kqscpoExpSMTIezetBTBKfWGv7TXPER.alFVAaZc33kT.');
INSERT INTO user_roles (user_id, role_id) VALUES (10, 1);
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (10, 'Налог на доход', 2983.05, '2025-01-28', 'PAID');
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (10, 'Налог на имущество', 9711.70, '2025-01-19', 'PENDING');
INSERT INTO properties (user_id, type, description, value) VALUES (10, 'Квартира', '###### Россия, Омск, Ломоносова улица, 189 кв. 935', 1651097.32);
INSERT INTO users (username, first_name, last_name, email, age, password) VALUES ('леонид.суворова', 'Олег', 'Федотов', 'евгении.мясников@yahoo.com', 54, '$2a$10$e4X47Hp5pCYHBmYktQuWWe8molDNEfWt0rRINeCfJnPWabNk2d71G');
INSERT INTO user_roles (user_id, role_id) VALUES (11, 1);
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (11, 'Налог на доход', 6295.59, '2025-01-10', 'PAID');
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (11, 'Налог на имущество', 3545.63, '2024-12-18', 'PENDING');
INSERT INTO properties (user_id, type, description, value) VALUES (11, 'Автомобиль', 'Foreigner', 2519947.98);
INSERT INTO users (username, first_name, last_name, email, age, password) VALUES ('матвей.тимофеева', 'Кира', 'Лыткин', 'игнатии.князев@yandex.ru', 49, '$2a$10$hO6x.FSMvWZHW2uB2UQgtOHcVSDp3AUx5OMdjiVpqrSizSLkiez7u');
INSERT INTO user_roles (user_id, role_id) VALUES (12, 1);
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (12, 'Налог на имущество', 6933.33, '2025-01-31', 'PAID');
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (12, 'Налог на доход', 1262.34, '2024-12-14', 'PENDING');
INSERT INTO properties (user_id, type, description, value) VALUES (12, 'Квартира', '###### Россия, Тверь, Чехова проспект, 341', 3193403.13);
INSERT INTO users (username, first_name, last_name, email, age, password) VALUES ('антонина.владимирова', 'Евгения', 'Пестова', 'иван.шилов@yahoo.com', 29, '$2a$10$EpmoYSDQaYV3o7oszrMU6.tIxsfOi4ooB.agwGIMxQiowwz6Xd0Ti');
INSERT INTO user_roles (user_id, role_id) VALUES (13, 1);
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (13, 'Налог на имущество', 9907.35, '2024-12-12', 'PAID');
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (13, 'Налог на доход', 3546.28, '2025-01-20', 'PENDING');
INSERT INTO properties (user_id, type, description, value) VALUES (13, 'Автомобиль', 'Cream', 1846042.62);
INSERT INTO users (username, first_name, last_name, email, age, password) VALUES ('ирина.гуляева', 'Валерия', 'Исаева', 'алексеи.кононов@mail.ru', 29, '$2a$10$qg8.v0PxI/BDizrRgIr2zuyhFNlSBBZG.waAp.HJMcgDwVu9TE1ny');
INSERT INTO user_roles (user_id, role_id) VALUES (14, 1);
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (14, 'Налог на имущество', 4935.84, '2024-12-11', 'PAID');
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (14, 'Налог на доход', 4100.09, '2024-12-20', 'PENDING');
INSERT INTO properties (user_id, type, description, value) VALUES (14, 'Квартира', '###### Россия, Москва, проспект Горная, 739 кв. 925', 4642617.23);
INSERT INTO users (username, first_name, last_name, email, age, password) VALUES ('юлия.брагин', 'Ксения', 'Коновалов', 'алина.захаров@yahoo.com', 47, '$2a$10$iV3s6oUTRGq.5XwfdyYUpeafguiWIgHu03hpy/k19clDnKqE1wz2.');
INSERT INTO user_roles (user_id, role_id) VALUES (15, 1);
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (15, 'Налог на доход', 5390.50, '2025-01-19', 'PAID');
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (15, 'Налог на имущество', 2273.01, '2025-01-10', 'PENDING');
INSERT INTO properties (user_id, type, description, value) VALUES (15, 'Автомобиль', 'The Police', 3273211.99);
INSERT INTO users (username, first_name, last_name, email, age, password) VALUES ('василий.рыбакова', 'Герман', 'Соколова', 'марина.одинцов@yahoo.com', 19, '$2a$10$TUqtFWAyLCAQNuIKs/HmJefUaETo/5SsrIHMxEG9thwDyQ7Pub77.');
INSERT INTO user_roles (user_id, role_id) VALUES (16, 1);
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (16, 'Налог на доход', 4452.01, '2025-01-04', 'PAID');
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (16, 'Налог на имущество', 8905.11, '2024-12-12', 'PENDING');
INSERT INTO properties (user_id, type, description, value) VALUES (16, 'Квартира', '###### Россия, Краснодар, Горная пл., 998 кв. 463', 3098154.76);
INSERT INTO users (username, first_name, last_name, email, age, password) VALUES ('антонида.воронцов', 'Альберт', 'Панова', 'зинаида.гуляева@ya.ru', 30, '$2a$10$VEIeKaI7JZKAY.U6vVr.U.pV/b32r08clN4N.a02RiSm0P0zzLBwi');
INSERT INTO user_roles (user_id, role_id) VALUES (17, 1);
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (17, 'Налог на имущество', 3884.14, '2024-12-21', 'PAID');
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (17, 'Налог на доход', 5563.55, '2024-12-14', 'PENDING');
INSERT INTO properties (user_id, type, description, value) VALUES (17, 'Автомобиль', 'Motley Crue', 3279918.49);
INSERT INTO users (username, first_name, last_name, email, age, password) VALUES ('василиса.воробьева', 'Лидия', 'Анисимов', 'дарья.жданова@gmail.com', 30, '$2a$10$I/zmSGuKIxIPTefw.TIyjubT2K2C6a/kzJlgyTlP5glbvYkmuOrgy');
INSERT INTO user_roles (user_id, role_id) VALUES (18, 1);
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (18, 'Налог на доход', 2525.63, '2025-02-04', 'PAID');
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (18, 'Налог на имущество', 7156.27, '2024-12-14', 'PENDING');
INSERT INTO properties (user_id, type, description, value) VALUES (18, 'Автомобиль', 'Rush', 2365898.56);
INSERT INTO users (username, first_name, last_name, email, age, password) VALUES ('алина.симонов', 'Ульяна', 'Никитин', 'ольга.афанасьева@ya.ru', 49, '$2a$10$JWY9eySIdFlmykkTgTWXgue4trPmZA0FWHYnJIX0sB1wlCeLAp8CW');
INSERT INTO user_roles (user_id, role_id) VALUES (19, 1);
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (19, 'Налог на доход', 7708.52, '2025-01-06', 'PAID');
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (19, 'Налог на имущество', 1352.64, '2024-12-27', 'PENDING');
INSERT INTO properties (user_id, type, description, value) VALUES (19, 'Автомобиль', 'Earth Wind and Fire', 4984969.72);
INSERT INTO users (username, first_name, last_name, email, age, password) VALUES ('зинаида.вишняков', 'Вероника', 'Кулаков', 'валерии.ермакова@ya.ru', 20, '$2a$10$BIh7DrwOnMwmSX.aYm3qj.EbtWAJ/Scc/MjjAdc2/fipFjtGBeEP2');
INSERT INTO user_roles (user_id, role_id) VALUES (20, 1);
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (20, 'Налог на доход', 5620.47, '2025-01-28', 'PAID');
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (20, 'Налог на имущество', 3337.30, '2025-01-29', 'PENDING');
INSERT INTO properties (user_id, type, description, value) VALUES (20, 'Квартира', '###### Россия, Владивосток, пр. Карла Маркса, 790', 3853355.01);
INSERT INTO users (username, first_name, last_name, email, age, password) VALUES ('алёна.фокин', 'Валерий', 'Кулагин', 'виктор.русаков@hotmail.com', 56, '$2a$10$yzDAqFen/xs8EgwtWSfnguUAK0s62/1lC9UsT0LwyPITxn97e2d1u');
INSERT INTO user_roles (user_id, role_id) VALUES (21, 1);
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (21, 'Налог на имущество', 3594.49, '2025-02-03', 'PAID');
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (21, 'Налог на доход', 1570.07, '2025-01-05', 'PENDING');
INSERT INTO properties (user_id, type, description, value) VALUES (21, 'Автомобиль', 'The Orb', 3676066.25);
INSERT INTO users (username, first_name, last_name, email, age, password) VALUES ('иван.журавлева', 'Арина', 'Федосеев', 'роман.якушев@mail.ru', 46, '$2a$10$WmFwmmXtKywLoWsdV50bzOUl/sLLrf3j1EglbEmdsnXqyjXuIit4i');
INSERT INTO user_roles (user_id, role_id) VALUES (22, 1);
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (22, 'Налог на доход', 3954.20, '2025-01-22', 'PAID');
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (22, 'Налог на имущество', 3190.77, '2025-01-15', 'PENDING');
INSERT INTO properties (user_id, type, description, value) VALUES (22, 'Автомобиль', 'Judas Priest', 1178301.10);
INSERT INTO users (username, first_name, last_name, email, age, password) VALUES ('даниил.михайлов', 'Дмитрий', 'Карпов', 'елена.евдокимов@gmail.com', 22, '$2a$10$qsRiHOaYiwOS2nlhfvolWukn6tfc5IQJ9NLRczyWQC6MKmnXtCnEu');
INSERT INTO user_roles (user_id, role_id) VALUES (23, 1);
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (23, 'Налог на имущество', 9232.79, '2024-12-27', 'PAID');
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (23, 'Налог на доход', 6276.44, '2025-02-09', 'PENDING');
INSERT INTO properties (user_id, type, description, value) VALUES (23, 'Квартира', '###### Россия, Чебоксары, 8 Марта проспект, 490 кв. 529', 1248200.14);
INSERT INTO users (username, first_name, last_name, email, age, password) VALUES ('татьяна.кириллова', 'Василиса', 'Ковалева', 'игорь.марков@hotmail.com', 23, '$2a$10$E0RH0Y20WvX3pO/ZWY.T7O5OokpKLAy/ZbtEARd7iwhvjoNgkss8q');
INSERT INTO user_roles (user_id, role_id) VALUES (24, 1);
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (24, 'Налог на имущество', 7254.61, '2025-01-19', 'PAID');
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (24, 'Налог на доход', 6144.07, '2024-12-27', 'PENDING');
INSERT INTO properties (user_id, type, description, value) VALUES (24, 'Квартира', '###### Россия, Ставрополь, Мира пл., 806 кв. 280', 3094672.25);
INSERT INTO users (username, first_name, last_name, email, age, password) VALUES ('евгений.трофимова', 'Григорий', 'Наумов', 'маргарита.овчинников@mail.ru', 31, '$2a$10$JQWvQl8Paw3QWBBXzRAB9edpZbIZvP3bftR7nxBGf6jevgU8E/Kya');
INSERT INTO user_roles (user_id, role_id) VALUES (25, 1);
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (25, 'Налог на доход', 4350.47, '2025-01-05', 'PAID');
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (25, 'Налог на имущество', 8278.40, '2025-01-25', 'PENDING');
INSERT INTO properties (user_id, type, description, value) VALUES (25, 'Квартира', '###### Россия, Чебоксары, площадь Горная, 640 кв. 199', 1518883.37);
INSERT INTO users (username, first_name, last_name, email, age, password) VALUES ('роман.одинцова', 'Александра', 'Попов', 'регина.савин@yandex.ru', 49, '$2a$10$8VwFTVoACsa6vcGzdk4ywezCdD9QEQynFgrMFIT/PdiM0Guaw1ArK');
INSERT INTO user_roles (user_id, role_id) VALUES (26, 1);
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (26, 'Налог на доход', 3236.75, '2025-02-04', 'PAID');
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (26, 'Налог на имущество', 9117.49, '2025-01-16', 'PENDING');
INSERT INTO properties (user_id, type, description, value) VALUES (26, 'Автомобиль', 'Soundgarden', 4950197.43);
INSERT INTO users (username, first_name, last_name, email, age, password) VALUES ('лидия.емельянова', 'Матвей', 'Комиссарова', 'зинаида.комиссаров@yandex.ru', 45, '$2a$10$fc6WqzbTzKHbkRvNLvUiwOHmFTgfdjJ7P8Nci9.TN8t3qaWwftBnu');
INSERT INTO user_roles (user_id, role_id) VALUES (27, 1);
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (27, 'Налог на имущество', 5732.92, '2024-12-22', 'PAID');
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (27, 'Налог на доход', 7637.20, '2025-01-11', 'PENDING');
INSERT INTO properties (user_id, type, description, value) VALUES (27, 'Квартира', '###### Россия, Иркутск, Пионерская проспект, 946 кв. 753', 3831418.85);
INSERT INTO users (username, first_name, last_name, email, age, password) VALUES ('владимир.жуков', 'Артём', 'Мартынова', 'алексеи.дьячков@mail.ru', 44, '$2a$10$9NUQVBeQJLZhqx5NURrdNeS7sN4SrL9GJhtW01rgpAjz5WMNmzCBm');
INSERT INTO user_roles (user_id, role_id) VALUES (28, 1);
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (28, 'Налог на имущество', 7221.73, '2024-12-13', 'PAID');
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (28, 'Налог на доход', 7277.75, '2024-12-29', 'PENDING');
INSERT INTO properties (user_id, type, description, value) VALUES (28, 'Квартира', '###### Россия, Сочи, площадь Московская, 261 кв. 778', 2562842.24);
INSERT INTO users (username, first_name, last_name, email, age, password) VALUES ('григорий.фомин', 'Ярослав', 'Горбунов', 'валерии.кабанова@mail.ru', 57, '$2a$10$rd8wGIREeBvPu.cTNIVuvO8KHUZlvPSrqJ3iNhm0ejy/dx4qbzWBW');
INSERT INTO user_roles (user_id, role_id) VALUES (29, 1);
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (29, 'Налог на имущество', 5069.89, '2025-01-12', 'PAID');
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (29, 'Налог на доход', 6915.44, '2024-12-18', 'PENDING');
INSERT INTO properties (user_id, type, description, value) VALUES (29, 'Автомобиль', 'U2', 1568024.87);
INSERT INTO users (username, first_name, last_name, email, age, password) VALUES ('софия.евсеев', 'Алексей', 'Самойлова', 'иван.евдокимов@yahoo.com', 59, '$2a$10$/uo6vZ8eTQ3lUVw3BF0uleQKUa1w2/KWKiM1rf5.HiRDg2dR7DEh6');
INSERT INTO user_roles (user_id, role_id) VALUES (30, 1);
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (30, 'Налог на доход', 9811.98, '2025-01-03', 'PAID');
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (30, 'Налог на имущество', 6408.33, '2025-01-24', 'PENDING');
INSERT INTO properties (user_id, type, description, value) VALUES (30, 'Квартира', '###### Россия, Москва, Горького улица, 029', 1619241.06);
INSERT INTO users (username, first_name, last_name, email, age, password) VALUES ('алевтина.назарова', 'Фёдор', 'Афанасьева', 'надежда.мясников@yahoo.com', 22, '$2a$10$GVh9aWR8yXrt6LygHyM8g.Sl0pqfLDfbjuQy8Hi.RD3xY1OhM.cYq');
INSERT INTO user_roles (user_id, role_id) VALUES (31, 1);
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (31, 'Налог на имущество', 2790.41, '2025-01-13', 'PAID');
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (31, 'Налог на доход', 6094.21, '2025-01-21', 'PENDING');
INSERT INTO properties (user_id, type, description, value) VALUES (31, 'Автомобиль', 'The Carpenters', 2124187.42);
INSERT INTO users (username, first_name, last_name, email, age, password) VALUES ('роман.ситников', 'Оксана', 'Антонова', 'вадим.воронцов@hotmail.com', 44, '$2a$10$MQJLcLME6hOtzZ917osRAuZthmRivr/uOrQA6HvgcAXZS.sE5zK/a');
INSERT INTO user_roles (user_id, role_id) VALUES (32, 1);
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (32, 'Налог на имущество', 3343.08, '2024-12-26', 'PAID');
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (32, 'Налог на доход', 4021.65, '2025-01-04', 'PENDING');
INSERT INTO properties (user_id, type, description, value) VALUES (32, 'Квартира', '###### Россия, Ростов-на-Дону, Весенняя пр., 510', 982980.60);
INSERT INTO users (username, first_name, last_name, email, age, password) VALUES ('антон.лебедева', 'Елена', 'Никитина', 'зоя.беляев@yahoo.com', 38, '$2a$10$eah5prpoypRWP3uL5Jt78uF4A9Z.WsIHpcJztowLYTyPVfXbbRPga');
INSERT INTO user_roles (user_id, role_id) VALUES (33, 1);
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (33, 'Налог на имущество', 3061.68, '2025-01-05', 'PAID');
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (33, 'Налог на доход', 9572.56, '2025-01-10', 'PENDING');
INSERT INTO properties (user_id, type, description, value) VALUES (33, 'Автомобиль', 'The Orb', 2162825.03);
INSERT INTO users (username, first_name, last_name, email, age, password) VALUES ('елена.савина', 'Максим', 'Лобанова', 'ярослав.кузнецова@yandex.ru', 26, '$2a$10$enI40x7TLZ58U0vGpCUMae.IcUL07mmW2yOSvByTDPt04kgggUEcS');
INSERT INTO user_roles (user_id, role_id) VALUES (34, 1);
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (34, 'Налог на доход', 1134.91, '2025-02-03', 'PAID');
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (34, 'Налог на имущество', 2206.50, '2024-12-22', 'PENDING');
INSERT INTO properties (user_id, type, description, value) VALUES (34, 'Автомобиль', 'Genesis', 574542.20);
INSERT INTO users (username, first_name, last_name, email, age, password) VALUES ('вячеслав.васильева', 'Александр', 'Миронов', 'лидия.антонова@ya.ru', 37, '$2a$10$9WbLs1tQWCqylF0PbnzC.uaZ843hbBOpj5Cqghqm9ZfuXki8ISpLG');
INSERT INTO user_roles (user_id, role_id) VALUES (35, 1);
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (35, 'Налог на имущество', 6511.17, '2025-01-06', 'PAID');
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (35, 'Налог на доход', 1890.67, '2025-01-16', 'PENDING');
INSERT INTO properties (user_id, type, description, value) VALUES (35, 'Автомобиль', 'The Beach Boys', 2808059.36);
INSERT INTO users (username, first_name, last_name, email, age, password) VALUES ('оксана.аксенов', 'Роман', 'Хохлов', 'артем.терентьева@ya.ru', 38, '$2a$10$vt.o3FKKzn5zNg/AyT29cOmNldYhOIVsSHMkqROai4qzn1asX7gMu');
INSERT INTO user_roles (user_id, role_id) VALUES (36, 1);
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (36, 'Налог на имущество', 8446.47, '2025-02-07', 'PAID');
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (36, 'Налог на доход', 9434.37, '2025-01-08', 'PENDING');
INSERT INTO properties (user_id, type, description, value) VALUES (36, 'Квартира', '###### Россия, Оренбург, улица Полевая, 924', 779382.01);
INSERT INTO users (username, first_name, last_name, email, age, password) VALUES ('наталья.дьячкова', 'Лидия', 'Макаров', 'регина.воронова@gmail.com', 41, '$2a$10$0SL40.mlhyXnpTZWrBAHxudupZp3wc76DyLqR1EenNLI34wWc36z6');
INSERT INTO user_roles (user_id, role_id) VALUES (37, 1);
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (37, 'Налог на доход', 5822.61, '2025-01-23', 'PAID');
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (37, 'Налог на имущество', 6583.13, '2025-01-05', 'PENDING');
INSERT INTO properties (user_id, type, description, value) VALUES (37, 'Квартира', '###### Россия, Екатеринбург, Дружбы ул., 076', 3037006.69);
INSERT INTO users (username, first_name, last_name, email, age, password) VALUES ('юлия.осипов', 'Вадим', 'Дроздов', 'игнатии.владимиров@yandex.ru', 38, '$2a$10$SShmH/8RLQ.a.P48IFu0dOSsYTuw9RIWqf7rXTK12ZH2Sj8fi.GQG');
INSERT INTO user_roles (user_id, role_id) VALUES (38, 1);
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (38, 'Налог на доход', 9331.89, '2025-01-02', 'PAID');
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (38, 'Налог на имущество', 5677.58, '2025-01-24', 'PENDING');
INSERT INTO properties (user_id, type, description, value) VALUES (38, 'Автомобиль', 'Alice In Chains', 3997802.88);
INSERT INTO users (username, first_name, last_name, email, age, password) VALUES ('регина.бобров', 'Светлана', 'Гаврилова', 'даниил.туров@gmail.com', 33, '$2a$10$h7VR5wHBySJHlY/KwlvGSu6ocusdZGtseO7ya3ss6WimW4YdVLkMm');
INSERT INTO user_roles (user_id, role_id) VALUES (39, 1);
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (39, 'Налог на имущество', 4869.89, '2025-01-27', 'PAID');
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (39, 'Налог на доход', 6043.16, '2024-12-11', 'PENDING');
INSERT INTO properties (user_id, type, description, value) VALUES (39, 'Квартира', '###### Россия, Барнаул, Красноармейская улица, 631', 3811424.78);
INSERT INTO users (username, first_name, last_name, email, age, password) VALUES ('елена.игнатова', 'Леонид', 'Красильников', 'мария.логинова@hotmail.com', 28, '$2a$10$ZHb3HfYJsjj1RQMPft99EuldexPqUMjC2EAu8UiMQMEXNAjq70Nw.');
INSERT INTO user_roles (user_id, role_id) VALUES (40, 1);
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (40, 'Налог на доход', 5268.88, '2025-01-28', 'PAID');
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (40, 'Налог на имущество', 5679.25, '2025-02-01', 'PENDING');
INSERT INTO properties (user_id, type, description, value) VALUES (40, 'Квартира', '###### Россия, Рязань, Мичурина улица, 193 кв. 556', 2188703.03);
INSERT INTO users (username, first_name, last_name, email, age, password) VALUES ('андрей.устинова', 'Алевтина', 'Мартынов', 'жанна.романова@yandex.ru', 29, '$2a$10$sVGsA7atlwKr1pDfgkNiOeFK8yA4FFRaT8XePqHIWDWgaQzgQZ7zm');
INSERT INTO user_roles (user_id, role_id) VALUES (41, 1);
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (41, 'Налог на имущество', 3893.31, '2025-01-07', 'PAID');
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (41, 'Налог на доход', 3594.76, '2025-01-09', 'PENDING');
INSERT INTO properties (user_id, type, description, value) VALUES (41, 'Автомобиль', 'The Velvet Underground', 4507290.86);
INSERT INTO users (username, first_name, last_name, email, age, password) VALUES ('ульяна.давыдова', 'Любовь', 'Потапова', 'ярослав.лыткина@gmail.com', 49, '$2a$10$kxbpAZSghwlPFnx8DrVfu.sK.8VoFAplbJ.wU0KxEl1nR4ptNpsS.');
INSERT INTO user_roles (user_id, role_id) VALUES (42, 1);
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (42, 'Налог на имущество', 5635.36, '2025-01-03', 'PAID');
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (42, 'Налог на доход', 7784.50, '2025-02-07', 'PENDING');
INSERT INTO properties (user_id, type, description, value) VALUES (42, 'Квартира', '###### Россия, Санкт-Петербург, Космонавтов улица, 358', 3393434.38);
INSERT INTO users (username, first_name, last_name, email, age, password) VALUES ('варвара.капустина', 'Анжела', 'Бирюкова', 'татьяна.игнатов@gmail.com', 32, '$2a$10$QVKt1DDFZsSfyho20kLV3Ob1r3lD.ZjfQaaNhqx7DO5VvTlG8WwSG');
INSERT INTO user_roles (user_id, role_id) VALUES (43, 1);
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (43, 'Налог на имущество', 5406.89, '2025-02-06', 'PAID');
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (43, 'Налог на доход', 1596.92, '2025-01-14', 'PENDING');
INSERT INTO properties (user_id, type, description, value) VALUES (43, 'Квартира', '###### Россия, Воронеж, Механизаторов площадь, 457 кв. 627', 855485.46);
INSERT INTO users (username, first_name, last_name, email, age, password) VALUES ('анфиса.колобова', 'Даниил', 'Богданов', 'аркадии.макаров@gmail.com', 30, '$2a$10$RUn3nn.EiFlCe7UwbxtQb.i5mg/p1dOgBJff.GCA.gbUwXnEmDRlW');
INSERT INTO user_roles (user_id, role_id) VALUES (44, 1);
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (44, 'Налог на доход', 8235.51, '2025-01-15', 'PAID');
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (44, 'Налог на имущество', 1382.62, '2025-01-21', 'PENDING');
INSERT INTO properties (user_id, type, description, value) VALUES (44, 'Квартира', '###### Россия, Ижевск, Кирова проспект, 566', 1984122.05);
INSERT INTO users (username, first_name, last_name, email, age, password) VALUES ('екатерина.данилов', 'Дмитрий', 'Морозов', 'олег.рожков@mail.ru', 33, '$2a$10$WOYr5Q3Yy4.BqM3arG4Z9eYbVwjHfyUlJrIGa4JqyZp0cm1eN9CfS');
INSERT INTO user_roles (user_id, role_id) VALUES (45, 1);
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (45, 'Налог на имущество', 2218.75, '2025-01-23', 'PAID');
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (45, 'Налог на доход', 5633.36, '2025-01-06', 'PENDING');
INSERT INTO properties (user_id, type, description, value) VALUES (45, 'Автомобиль', 'ZZ Top', 3074585.63);
INSERT INTO users (username, first_name, last_name, email, age, password) VALUES ('сергей.дроздова', 'Геннадий', 'Сафонова', 'елизавета.потапова@yandex.ru', 44, '$2a$10$G732NgGPR6Be.kKhlb7WcuJ0U.Z1vh5Zz7trUYuivNzneGdcTlTkW');
INSERT INTO user_roles (user_id, role_id) VALUES (46, 1);
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (46, 'Налог на доход', 1326.35, '2025-01-15', 'PAID');
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (46, 'Налог на имущество', 2383.50, '2024-12-16', 'PENDING');
INSERT INTO properties (user_id, type, description, value) VALUES (46, 'Автомобиль', 'The Doors', 3040524.65);
INSERT INTO users (username, first_name, last_name, email, age, password) VALUES ('владимир.кудрявцева', 'Галина', 'Федотова', 'евгении.никифоров@mail.ru', 58, '$2a$10$ODiR2u9HO.gxbpmOjttzSeAF.f3Jnf./0rOzjHhdL2VM4TlntRsTm');
INSERT INTO user_roles (user_id, role_id) VALUES (47, 1);
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (47, 'Налог на доход', 2129.72, '2025-02-08', 'PAID');
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (47, 'Налог на имущество', 1508.82, '2025-02-03', 'PENDING');
INSERT INTO properties (user_id, type, description, value) VALUES (47, 'Автомобиль', 'Harold Melvin and the Blue Notes', 1443749.54);
INSERT INTO users (username, first_name, last_name, email, age, password) VALUES ('денис.панфилова', 'Василиса', 'Романов', 'леонид.русакова@mail.ru', 50, '$2a$10$N92LAehr4BrnpG/Han0z6.UBZ9EZWPNBfB5OYbeR04Fp5s7Fc8fla');
INSERT INTO user_roles (user_id, role_id) VALUES (48, 1);
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (48, 'Налог на доход', 1583.66, '2025-01-10', 'PAID');
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (48, 'Налог на имущество', 1221.90, '2025-01-03', 'PENDING');
INSERT INTO properties (user_id, type, description, value) VALUES (48, 'Квартира', '###### Россия, Курск, улица Гоголя, 450 кв. 991', 1304453.11);
INSERT INTO users (username, first_name, last_name, email, age, password) VALUES ('валентина.комарова', 'Борис', 'Молчанова', 'геннадии.соболев@yandex.ru', 37, '$2a$10$PlF27doJRMJ.x17wgYqoReQo.E2ZI3TWn5k5QKbYkYDym0q9CP8le');
INSERT INTO user_roles (user_id, role_id) VALUES (49, 1);
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (49, 'Налог на доход', 1644.45, '2024-12-30', 'PAID');
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (49, 'Налог на имущество', 7008.10, '2025-01-04', 'PENDING');
INSERT INTO properties (user_id, type, description, value) VALUES (49, 'Автомобиль', 'The Carpenters', 2493985.40);
INSERT INTO users (username, first_name, last_name, email, age, password) VALUES ('иван.матвеев', 'Мария', 'Титов', 'степан.шестаков@mail.ru', 33, '$2a$10$EYyflDcj4CuMba.ntrdK1ODG6bmM9lxPqC/Op3aCj928VP/ID358W');
INSERT INTO user_roles (user_id, role_id) VALUES (50, 1);
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (50, 'Налог на доход', 1575.93, '2025-01-24', 'PAID');
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (50, 'Налог на имущество', 8414.50, '2025-02-05', 'PENDING');
INSERT INTO properties (user_id, type, description, value) VALUES (50, 'Квартира', '###### Россия, Волгоград, пл. Клубная, 675', 1482844.02);
INSERT INTO users (username, first_name, last_name, email, age, password) VALUES ('артём.данилова', 'Леонид', 'Морозова', 'анфиса.щербаков@yahoo.com', 48, '$2a$10$rVOY/fvZMQ4YxfRch.GGuunXhdDkRl2ErUWEotNuPGshCrqC.sWiC');
INSERT INTO user_roles (user_id, role_id) VALUES (51, 1);
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (51, 'Налог на имущество', 5919.24, '2024-12-25', 'PAID');
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (51, 'Налог на доход', 5718.62, '2024-12-22', 'PENDING');
INSERT INTO properties (user_id, type, description, value) VALUES (51, 'Автомобиль', 'Blondie', 3230779.25);
INSERT INTO users (username, first_name, last_name, email, age, password) VALUES ('леонид.зайцев', 'Виктория', 'Буров', 'валентин.фролова@mail.ru', 39, '$2a$10$D1T0F1/AMzzVnJ8RIYG.Hu.Z35GRUWOqMu0WdpK.TaDv/LeQ2UWru');
INSERT INTO user_roles (user_id, role_id) VALUES (52, 1);
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (52, 'Налог на имущество', 3635.51, '2025-02-04', 'PAID');
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (52, 'Налог на доход', 6364.88, '2025-01-18', 'PENDING');
INSERT INTO properties (user_id, type, description, value) VALUES (52, 'Автомобиль', 'Steely Dan', 2850888.34);
INSERT INTO users (username, first_name, last_name, email, age, password) VALUES ('ольга.зиновьев', 'Анастасия', 'Третьяков', 'алина.жукова@mail.ru', 32, '$2a$10$aGT5zE.91sd7Wc0D3QIiZOLuH8kvE7sqMCX2XxiMOKlqrH/1ABCEe');
INSERT INTO user_roles (user_id, role_id) VALUES (53, 1);
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (53, 'Налог на доход', 6610.24, '2025-01-13', 'PAID');
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (53, 'Налог на имущество', 5196.85, '2025-01-17', 'PENDING');
INSERT INTO properties (user_id, type, description, value) VALUES (53, 'Автомобиль', 'The Carpenters', 4147553.52);
INSERT INTO users (username, first_name, last_name, email, age, password) VALUES ('клавдия.шубин', 'Георгий', 'Боброва', 'виталии.чернова@yahoo.com', 59, '$2a$10$ju8I3aU/x9Jl.SoDq.K4UuAhGlGqlHnLjxEn9OV8OqFgNvUhQ2uqG');
INSERT INTO user_roles (user_id, role_id) VALUES (54, 1);
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (54, 'Налог на доход', 3304.44, '2025-01-03', 'PAID');
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (54, 'Налог на имущество', 9288.37, '2025-01-22', 'PENDING');
INSERT INTO properties (user_id, type, description, value) VALUES (54, 'Квартира', '###### Россия, Ульяновск, Южная проспект, 329', 3782712.65);
INSERT INTO users (username, first_name, last_name, email, age, password) VALUES ('василиса.кабанов', 'Евгений', 'Михайлова', 'денис.овчинникова@ya.ru', 50, '$2a$10$JtxWJg18ePAVRioai2onSuRTBAjpGoLO8unUHvw68.h1QrwDnNqzu');
INSERT INTO user_roles (user_id, role_id) VALUES (55, 1);
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (55, 'Налог на имущество', 6367.25, '2024-12-29', 'PAID');
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (55, 'Налог на доход', 4033.14, '2024-12-25', 'PENDING');
INSERT INTO properties (user_id, type, description, value) VALUES (55, 'Квартира', '###### Россия, Владивосток, пр. Молодежная, 440', 834536.44);
INSERT INTO users (username, first_name, last_name, email, age, password) VALUES ('лидия.воронцов', 'Нина', 'Марков', 'екатерина.калашников@ya.ru', 31, '$2a$10$23G0s.RnuaXQkKj478QAe.GnF4jY1ic/tlt2ukc3JjmN08OgoVSAK');
INSERT INTO user_roles (user_id, role_id) VALUES (56, 1);
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (56, 'Налог на имущество', 6481.92, '2025-02-02', 'PAID');
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (56, 'Налог на доход', 8950.06, '2024-12-11', 'PENDING');
INSERT INTO properties (user_id, type, description, value) VALUES (56, 'Квартира', '###### Россия, Пермь, Садовая улица, 105 кв. 906', 2109668.14);
INSERT INTO users (username, first_name, last_name, email, age, password) VALUES ('леонид.логинов', 'Сергей', 'Королева', 'альберт.семенова@mail.ru', 44, '$2a$10$NjaAMBHQD6UAD5j5dVz48.p1ejASh6LIyd8wRyTxKpTBi.r/32EsO');
INSERT INTO user_roles (user_id, role_id) VALUES (57, 1);
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (57, 'Налог на имущество', 9476.92, '2025-01-15', 'PAID');
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (57, 'Налог на доход', 2339.96, '2024-12-27', 'PENDING');
INSERT INTO properties (user_id, type, description, value) VALUES (57, 'Квартира', '###### Россия, Ярославль, Некрасова ул., 777 кв. 742', 3932930.83);
INSERT INTO users (username, first_name, last_name, email, age, password) VALUES ('степан.филатов', 'Леонид', 'Панфилов', 'юлия.зыков@ya.ru', 47, '$2a$10$CCPNK3p3ZOy5N0mhiuyr/OKVkSv5tfhqKfsJbr0EF34Wt2eJhDZKW');
INSERT INTO user_roles (user_id, role_id) VALUES (58, 1);
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (58, 'Налог на имущество', 1130.20, '2025-01-24', 'PAID');
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (58, 'Налог на доход', 7440.24, '2025-01-03', 'PENDING');
INSERT INTO properties (user_id, type, description, value) VALUES (58, 'Квартира', '###### Россия, Санкт-Петербург, ул. Восточная, 963 кв. 809', 1955576.80);
INSERT INTO users (username, first_name, last_name, email, age, password) VALUES ('константин.кононова', 'Галина', 'Шарапов', 'алексеи.сафонов@mail.ru', 50, '$2a$10$m5BuL8InJDWeAp8H1ZR6NOmG3ZY0NXcr6zFxiylr19wHv.zHWhHJC');
INSERT INTO user_roles (user_id, role_id) VALUES (59, 1);
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (59, 'Налог на доход', 9679.73, '2024-12-27', 'PAID');
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (59, 'Налог на имущество', 3447.84, '2025-02-07', 'PENDING');
INSERT INTO properties (user_id, type, description, value) VALUES (59, 'Квартира', '###### Россия, Оренбург, ул. Клубная, 335', 4856629.24);
INSERT INTO users (username, first_name, last_name, email, age, password) VALUES ('юлия.крюков', 'Игнатий', 'Герасимова', 'ярослав.павлов@hotmail.com', 47, '$2a$10$ClWAW8dBX4r8HB1UIpJqdumlDeQs9Adt26eP7zUqHf1pBJEpPkXTm');
INSERT INTO user_roles (user_id, role_id) VALUES (60, 1);
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (60, 'Налог на доход', 2498.91, '2025-01-08', 'PAID');
INSERT INTO tax_payments (user_id, tax_type, amount, due_date, status) VALUES (60, 'Налог на имущество', 3957.66, '2025-01-09', 'PENDING');
INSERT INTO properties (user_id, type, description, value) VALUES (60, 'Квартира', '###### Россия, Казань, Весенняя ул., 398 кв. 192', 1326265.33);
